### ISSUE TITLE
the tool cannot apply on pg process on production server ?

### ISSUE THREAD

**Issue by baiwfg2** [jnidzwetzki/pg-lock-tracer#171]
> In order to be able to attach the uprobes to the functions, they should not to be optimized away (e.g., inlined) during the compilation of PostgreSQL. Otherwise errors like Unable to locate function XXX will occur when pg_lock_tracer is started

As it says, pg binary on production is built with optimizations definitely (-O2, or -O3). So we can't use it in that situation ? 

Put it in another way, is it true that ebpf-derived tool cannot apply to release-built binary using in production environment if uprobes need to be monitored ? Because most of time we don't know whether a given symbol is optimized out or inlined, causing our uprobes useless.

**Comment by jnidzwetzki** [comment]
Hi @baiwfg2,

It is hard to define exactly what 'binary on production' means. However, most of the time, these kinds of binaries are highly optimized; functions are inlined, and no UProbles can be attached. Therefore, I recommend using unoptimized builds for this kind of UProbe-based observation.
