### ISSUE TITLE
why pg_lock_tracer need -r whereas lw_lock,row_lock tool don't ?

### ISSUE THREAD

**Issue by baiwfg2** [jnidzwetzki/pg-lock-tracer#172]
According to README page, I find that only `pg_lock_tracer ` do with `-r` option, whereas the other two don't.

I try to remove `-r` from  `pg_lock_tracer ` command, and it won't output any more.

**Comment by jnidzwetzki** [comment]
Hi @baiwfg2,

> I try to remove -r from pg_lock_tracer command, and it won't output any more.

I cannot reproduce the behavior in my local environment. Could you post the exact command you used?
