### ISSUE TITLE
README is missing a couple of details

### ISSUE THREAD

**Issue by petergeoghegan** [jnidzwetzki/pg-lock-tracer#22]
I notice that the README refers to `requirements.txt`, when it should refer to `requirements_dev.txt`. There is also a notable omission in the installation instructions: a `pip install pg-lock-tracer` step seems to have been overlooked.

**Comment by jnidzwetzki** [comment]
Hello @petergeoghegan,

Thank you for pointing this out. I will correct this in a PR soon.
