### ISSUE TITLE
Seems this repo can work in Python3.8 and pg12, pg13

### ISSUE THREAD

**Issue by yihong0618** [jnidzwetzki/pg-lock-tracer#24]
My env is python3.8 and I notice that [pg-lock-tracer](https://github.com/jnidzwetzki/pg-lock-tracer) can only run bigger than 3.9
so I clone and change the `setup.cfg` to python3.8 and it worked, also for pg12

--- 

I fork this repo and run actions for pg12 pg13 and python3.8 they all passed 
you can track my passed test:  https://github.com/yihong0618/pg-lock-tracer/actions/runs/4029607444

**Comment by jnidzwetzki** [comment]
Hello @yihong0618,

Thank you very much for your contribution. I will merge your PR in a few minutes. I have never tested the lock tracer with PostgreSQL 12 or 13. Feel free to open a PR that adds the PostgreSQL versions to the [build matrix](https://github.com/jnidzwetzki/pg-lock-tracer/blob/d70cfa6862b0f8b483ec3714e930960caf4bffb8/.github/workflows/integration_tests.yml#L14) and the `README.md` file.

Best regards
   Jan

**Comment by yihong0618** [comment]
@jnidzwetzki copy that will open another do that, thanks.
